//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookList
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int id { get; set444; }
        public string isbn { get; set; }
        public string bookName { get; set; }
        public string author { get; set; }
        public string press { get; set; }
        public System.DateTime pressDate { get; set; }
        public Nullable<double> price { get; set; }
        public string barcode { get; set; }
        public string size { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<int> format { get; set; }
    }
}
